# Form implementation generated from reading ui file 'GameView.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GameWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(490, 655)
        MainWindow.setStyleSheet("background-color: rgb(113, 113, 118);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(30, 40, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.nameLabel.setFont(font)
        self.nameLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.nameLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.nameLabel.setObjectName("nameLabel")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 200, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-radius: 25px;\n"
"background: #FFFFFF;\n"
"border: 2px solid #FFFFFF;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 200, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border-radius: 25px;\n"
"background: #FFFFFF;\n"
"border: 2px solid #FFFFFF;")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 200, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("border-radius: 25px;\n"
"background: #FFFFFF;\n"
"border: 2px solid #FFFFFF;")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(360, 200, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("border-radius: 25px;\n"
"background: #FFFFFF;\n"
"border: 2px solid #FFFFFF;")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 310, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("border-radius: 25px;\n"
"background: #FFFFFF;\n"
"border: 2px solid #FFFFFF;")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(250, 310, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("border-radius: 25px;\n"
"background: #FFFFFF;\n"
"border: 2px solid #FFFFFF;")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(140, 310, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("border-radius: 25px;\n"
"background: #FFFFFF;\n"
"border: 2px solid #FFFFFF;")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(360, 310, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("border-radius: 25px;\n"
"background: #FFFFFF;\n"
"border: 2px solid #FFFFFF;")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(30, 420, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("border-radius: 25px;\n"
"background: #FFFFFF;\n"
"border: 2px solid #FFFFFF;")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(250, 420, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("border-radius: 25px;\n"
"background: #FFFFFF;\n"
"border: 2px solid #FFFFFF;")
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(140, 420, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("border-radius: 25px;\n"
"background: #FFFFFF;\n"
"border: 2px solid #FFFFFF;")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(360, 420, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("border-radius: 25px;\n"
"background: #FFFFFF;\n"
"border: 2px solid #FFFFFF;")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(30, 530, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("border-radius: 25px;\n"
"background: #FFFFFF;\n"
"border: 2px solid #FFFFFF;")
        self.pushButton_13.setText("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(250, 530, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("border-radius: 25px;\n"
"background: #FFFFFF;\n"
"border: 2px solid #FFFFFF;")
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(140, 530, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("border-radius: 25px;\n"
"background: #FFFFFF;\n"
"border: 2px solid #FFFFFF;")
        self.pushButton_15.setText("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(360, 530, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("border-radius: 25px;\n"
"background: #FFFFFF;\n"
"border: 2px solid #FFFFFF;")
        self.pushButton_16.setText("")
        self.pushButton_16.setObjectName("pushButton_16")
        self.moveLabel = QtWidgets.QLabel(self.centralwidget)
        self.moveLabel.setGeometry(QtCore.QRect(30, 100, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.moveLabel.setFont(font)
        self.moveLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.moveLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.moveLabel.setObjectName("moveLabel")
        self.surrender_button = QtWidgets.QPushButton(self.centralwidget)
        self.surrender_button.setGeometry(QtCore.QRect(310, 40, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.surrender_button.setFont(font)
        self.surrender_button.setStyleSheet("border-radius: 15px;\n"
"background: #FFFFFF;\n"
"border: 2px solid #FFFFFF;\n"
"color: rgb(113, 113, 118);")
        self.surrender_button.setObjectName("surrender_button")
        self.restart_button = QtWidgets.QPushButton(self.centralwidget)
        self.restart_button.setGeometry(QtCore.QRect(310, 110, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.restart_button.setFont(font)
        self.restart_button.setStyleSheet("border-radius: 15px;\n"
"background: #FFFFFF;\n"
"border: 2px solid #FFFFFF;\n"
"color: rgb(113, 113, 118);")
        self.restart_button.setObjectName("restart_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Game"))
        self.nameLabel.setText(_translate("MainWindow", "Nickname"))
        self.moveLabel.setText(_translate("MainWindow", "move"))
        self.surrender_button.setText(_translate("MainWindow", "Leave"))
        self.restart_button.setText(_translate("MainWindow", "Restart"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
