# Form implementation generated from reading ui file 'RegistrationView.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RegistrationView(object):
    def setupUi(self, RegistrationView):
        RegistrationView.setObjectName("RegistrationView")
        RegistrationView.resize(490, 655)
        RegistrationView.setStyleSheet("background-color: rgb(113, 113, 118);")
        self.centralwidget = QtWidgets.QWidget(RegistrationView)
        self.centralwidget.setObjectName("centralwidget")
        self.nickname_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.nickname_line_edit.setGeometry(QtCore.QRect(100, 280, 291, 71))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.nickname_line_edit.setFont(font)
        self.nickname_line_edit.setStyleSheet("border: 2px solid #FFFFFF;\n"
"border-radius: 15px;\n"
"background: #FFFFFF;\n"
"color: rgb(113, 113, 118);")
        self.nickname_line_edit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.nickname_line_edit.setObjectName("nickname_line_edit")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(90, 110, 311, 141))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.create_button = QtWidgets.QPushButton(self.centralwidget)
        self.create_button.setGeometry(QtCore.QRect(140, 380, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.create_button.setFont(font)
        self.create_button.setStyleSheet("border: 2px solid #FFFFFF;\n"
"border-radius: 15px;\n"
"background: #FFFFFF;\n"
"color: rgb(113, 113, 118);")
        self.create_button.setObjectName("create_button")
        RegistrationView.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RegistrationView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 490, 24))
        self.menubar.setObjectName("menubar")
        RegistrationView.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RegistrationView)
        self.statusbar.setObjectName("statusbar")
        RegistrationView.setStatusBar(self.statusbar)

        self.retranslateUi(RegistrationView)
        QtCore.QMetaObject.connectSlotsByName(RegistrationView)

    def retranslateUi(self, RegistrationView):
        _translate = QtCore.QCoreApplication.translate
        RegistrationView.setWindowTitle(_translate("RegistrationView", "MainWindow"))
        self.title_label.setText(_translate("RegistrationView", "Enter your\n"
"nickname"))
        self.create_button.setText(_translate("RegistrationView", "Game"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegistrationView = QtWidgets.QMainWindow()
    ui = Ui_RegistrationView()
    ui.setupUi(RegistrationView)
    RegistrationView.show()
    sys.exit(app.exec())
